### ISSUE TITLE
User Story: Search for recipes

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/forkify#1]
As a **User**, I can **search for recipes** so that I **can find new ideas for meals**.

## Acceptance Criteria

- When I input a specific ingredient or dish name into the search bar, the system should return relevant and accurate results.
- The system should allow me to filter and sort the search results.
-  Upon selecting a specific recipe from the search results, I should be provided with detailed information.

## Tasks

- [x] -  Search functionality: input field to send request to API with searched
keywords.
- [x] - Display results with pagination.
- [x] - Display recipe with cooking time, servings and ingredients.

## Epic

Placeholder_Epic_Name - Epic_Issue_Number
