### ISSUE TITLE
User Story: Create my own recipes

### ISSUE THREAD

**Issue by llancruzz** [llancruzz/forkify#4]
As a **User**, I can **be able to create my own recipes** so that I **have them all
organized in the same app**.

## Acceptance Criteria

- The app should provide a user-friendly interface that allows users to input and organize their own recipes.
- The app should offer a dedicated section or personal recipe collection where users can view and manage their created recipes.

## Tasks

- [ ] - User can upload own recipes. 
- [ ] - User recipes will automatically be bookmarked. 
- [ ] - User can only see their own recipes, not recipes from other users.

## Epic

Placeholder_Epic_Name - Epic_Issue_Number
